name: Spark Scaffold CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ hashFiles('**/build.sbt') }}
          ${{ runner.os }}-maven
          ${{ runner.os }}-
    - name: Cache Ivy2
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
          ${{ runner.os }}-ivy2
          ${{ runner.os }}-
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          ${{ runner.os }}-sbt
          ${{ runner.os }}-
    - name: Cache Coursier
      uses: actions/cache@v1
      with:
        path: ~/.coursier
        key: ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-coursier-${{ hashFiles('**/build.sbt') }}
          ${{ runner.os }}-coursier
          ${{ runner.os }}-
    - name: Run tests
      run: sbt test
    - name: Package
      run: make build-spark-jar
    - name: Persist the Jar file
      uses: actions/upload-artifact@v1
      with:
        name: fat-jar
        path: package

